// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDl5WjSUgC8wYmBtf3nKr8wEgLte6cputE',
    appId: '1:132750573187:web:5a63c9a97b6651cb1da5b6',
    messagingSenderId: '132750573187',
    projectId: 'clashproject-12e13',
    authDomain: 'clashproject-12e13.firebaseapp.com',
    storageBucket: 'clashproject-12e13.firebasestorage.app',
    measurementId: 'G-TEYV6QLSTX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAt24PG4S3-u9X3jnwabFCbM5QTD8f4s5w',
    appId: '1:132750573187:android:1b224e2c17cb6f071da5b6',
    messagingSenderId: '132750573187',
    projectId: 'clashproject-12e13',
    storageBucket: 'clashproject-12e13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0sV5G8cza2w77MI1UO3lRzEBe36xMEYU',
    appId: '1:132750573187:ios:b37d1b0669b4ae001da5b6',
    messagingSenderId: '132750573187',
    projectId: 'clashproject-12e13',
    storageBucket: 'clashproject-12e13.firebasestorage.app',
    iosBundleId: 'com.example.clashproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0sV5G8cza2w77MI1UO3lRzEBe36xMEYU',
    appId: '1:132750573187:ios:b37d1b0669b4ae001da5b6',
    messagingSenderId: '132750573187',
    projectId: 'clashproject-12e13',
    storageBucket: 'clashproject-12e13.firebasestorage.app',
    iosBundleId: 'com.example.clashproject',
  );
}
